// Index documentaire des écrans — généré par scripts/convert-stitch.mjs. Ne pas éditer.

export type MetaEcran = { slug: string; titre: string; domaine: string };

export const metaEcrans: MetaEcran[] = [
  { slug: "accueil_portail_dioc_sain_cvav_platform", titre: "Accueil portail dioc sain cvav platform", domaine: "Portail & Inscriptions" },
  { slug: "accus_de_r_ception_a4_imprimable_export_pdf_ange_emmanuel_kouame", titre: "Accus de r ception a4 imprimable export pdf ange emmanuel kouame", domaine: "Chancellerie & Bibliothèque" },
  { slug: "accus_de_r_ception_t_l_com_dlr_48_48_sms_pastoraux_d_livr_s_p_lerinage_2025", titre: "Accus de r ception t l com dlr 48 48 sms pastoraux d livr s p lerinage 2025", domaine: "Camps & Pèlerinages" },
  { slug: "accus_de_r_ception_t_l_com_dlr_relance_sms_4_4_d_livr_s_console_paroissiale", titre: "Accus de r ception t l com dlr relance sms 4 4 d livr s console paroissiale", domaine: "Console Paroissiale" },
  { slug: "accus_de_r_ception_t_l_com_sms_d_livr_au_p_re", titre: "Accus de r ception t l com sms d livr au p re", domaine: "Camps & Pèlerinages" },
  { slug: "acte_notari_solennel_de_cl_ture_scellement_canonique_du_trimestre_1_pdf_a_3b", titre: "Acte notari solennel de cl ture scellement canonique du trimestre 1 pdf a 3b", domaine: "Registres & Tabularium" },
  { slug: "administration_des_r_f_rentiels_nouvelle_entr_e_types_d_activit_cvav_platform", titre: "Administration des r f rentiels nouvelle entr e types d activit cvav platform", domaine: "Administration & Référentiels" },
  { slug: "administration_des_r_f_rentiels_syst_me_crud_cvav_platform", titre: "Administration des r f rentiels syst me crud cvav platform", domaine: "Administration & Référentiels" },
  { slug: "administration_des_r_f_rentiels_types_d_activit_cvav_platform", titre: "Administration des r f rentiels types d activit cvav platform", domaine: "Administration & Référentiels" },
  { slug: "affectation_d_ploiement_des_animateurs_brevet_s_volontaires_p_lerinage_2025", titre: "Affectation d ploiement des animateurs brevet s volontaires p lerinage 2025", domaine: "Camps & Pèlerinages" },
  { slug: "alerte_incident_soin_terrain_appel_clair_patrouille_saint_joseph", titre: "Alerte incident soin terrain appel clair patrouille saint joseph", domaine: "Terrain & Sécurité" },
  { slug: "alerte_usurpation_titre_r_voqu_scr_pub_01_contr_le_canonique", titre: "Alerte usurpation titre r voqu scr pub 01 contr le canonique", domaine: "Terrain & Sécurité" },
  { slug: "appel_clair_actualis_25_25_incident_consign_r_int_gration_christian_ak", titre: "Appel clair actualis 25 25 incident consign r int gration christian ak", domaine: "Terrain & Sécurité" },
  { slug: "appel_clair_contr_le_instantan_25_25_patrouille_saint_joseph", titre: "Appel clair contr le instantan 25 25 patrouille saint joseph", domaine: "Terrain & Sécurité" },
  { slug: "appel_direct_en_cours_tuteur_paul_kouam_brou_amenan_gr_ce", titre: "Appel direct en cours tuteur paul kouam brou amenan gr ce", domaine: "Terrain & Sécurité" },
  { slug: "arbitrage_canonique_conflit_de_doublon_wf_02_ange_gabriel_traor", titre: "Arbitrage canonique conflit de doublon wf 02 ange gabriel traor", domaine: "Gouvernance & Synodalité" },
  { slug: "arborescence_gestion_des_sections_branches_et_quipes_scr_gov_03_cath_drale", titre: "Arborescence gestion des sections branches et quipes scr gov 03 cath drale", domaine: "Gouvernance & Synodalité" },
  { slug: "arborescence_organisation_des_sections_13e_patrouille_rig_e_cath_drale_christ", titre: "Arborescence organisation des sections 13e patrouille rig e cath drale christ", domaine: "Terrain & Sécurité" },
  { slug: "archives_canoniques_tabularium_dioc_sain_superadmin_dioc_se_de_daloa", titre: "Archives canoniques tabularium dioc sain superadmin dioc se de daloa", domaine: "Registres & Tabularium" },
  { slug: "bascule_d_ann_e_pastorale_cl_ture_synodale_scr_roll_01_dioc_se_de_daloa", titre: "Bascule d ann e pastorale cl ture synodale scr roll 01 dioc se de daloa", domaine: "Gouvernance & Synodalité" },
  { slug: "biblioth_que_documentaire_dioc_saine_scr_doc_01_cvav_platform", titre: "Biblioth que documentaire dioc saine scr doc 01 cvav platform", domaine: "Chancellerie & Bibliothèque" },
  { slug: "biblioth_que_documentaire_notice_protocole_sanitaire_2025_san_biv_2025_02", titre: "Biblioth que documentaire notice protocole sanitaire 2025 san biv 2025 02", domaine: "Chancellerie & Bibliothèque" },
  { slug: "bilan_financier_consolid_par_doyenn_lecture_seule_superadmin_dioc_se_de_daloa", titre: "Bilan financier consolid par doyenn lecture seule superadmin dioc se de daloa", domaine: "Finances & Cotisations" },
  { slug: "bilan_financier_consolid_par_doyenn_superadmin_dioc_se_de_daloa", titre: "Bilan financier consolid par doyenn superadmin dioc se de daloa", domaine: "Finances & Cotisations" },
  { slug: "bilan_financier_provisoire_dioc_sain_export_archivage_pdf_a_3b_p_lerinage_2025", titre: "Bilan financier provisoire dioc sain export archivage pdf a 3b p lerinage 2025", domaine: "Finances & Cotisations" },
  { slug: "bon_de_contr_le_sanitaire_a4_imprimable_sandrine_kanga", titre: "Bon de contr le sanitaire a4 imprimable sandrine kanga", domaine: "Chancellerie & Bibliothèque" },
  { slug: "bordereau_d_margement_a4_quittance_orange_money_amenan_gr_ce_brou", titre: "Bordereau d margement a4 quittance orange money amenan gr ce brou", domaine: "Finances & Cotisations" },
  { slug: "bordereau_d_margement_paroissial_a4_vavoua_6_000_fcfa_p_lerinage_2025", titre: "Bordereau d margement paroissial a4 vavoua 6 000 fcfa p lerinage 2025", domaine: "Chancellerie & Bibliothèque" },
  { slug: "bordereau_d_margement_paroissial_a4_zoukougbeu_9_000_fcfa_p_lerinage_2025", titre: "Bordereau d margement paroissial a4 zoukougbeu 9 000 fcfa p lerinage 2025", domaine: "Chancellerie & Bibliothèque" },
  { slug: "brevet_cadet_officiel_a4_imprimable_mo_se_assi_cvav_platform", titre: "Brevet cadet officiel a4 imprimable mo se assi cvav platform", domaine: "Pédagogie & Investiture" },
  { slug: "carnet_de_progression_p_dagogique_num_ris_feuillet_04_08_mo_se_koffi_assi", titre: "Carnet de progression p dagogique num ris feuillet 04 08 mo se koffi assi", domaine: "Espace Militant" },
  { slug: "carnet_de_progression_p_dagogique_num_ris_pdf_a_3b_mo_se_koffi_assi", titre: "Carnet de progression p dagogique num ris pdf a 3b mo se koffi assi", domaine: "Espace Militant" },
  { slug: "carte_de_membre_pvc_num_rique_mo_se_assi_cvav_platform", titre: "Carte de membre pvc num rique mo se assi cvav platform", domaine: "Espace Militant" },
  { slug: "carte_officielle_pvc_scell_e_jean_philippe_kanga_d_livrance_pastorale", titre: "Carte officielle pvc scell e jean philippe kanga d livrance pastorale", domaine: "Registres & Tabularium" },
  { slug: "carte_pastorale_dioc_saine_pdf_a_3b_d_coupage_canonique_des_5_doyenn_s", titre: "Carte pastorale dioc saine pdf a 3b d coupage canonique des 5 doyenn s", domaine: "Chancellerie & Bibliothèque" },
  { slug: "carte_valid_e_mise_succ_s_du_scellement_pastorale_dossier_ange_emmanuel", titre: "Carte valid e mise succ s du scellement pastorale dossier ange emmanuel", domaine: "Registres & Tabularium" },
  { slug: "centre_d_exportation_excel_csv_registre_paroissial_consolid", titre: "Centre d exportation excel csv registre paroissial consolid", domaine: "Registres & Tabularium" },
  { slug: "centre_d_exportation_excel_csv_registre_paroissial_consolid_143_inscrits", titre: "Centre d exportation excel csv registre paroissial consolid 143 inscrits", domaine: "Registres & Tabularium" },
  { slug: "centre_de_notifications_pastorales_alertes_syst_me_scr_not_01_cvav_platform", titre: "Centre de notifications pastorales alertes syst me scr not 01 cvav platform", domaine: "Espace Militant" },
  { slug: "centre_de_statistiques_exports_multi_niveaux_scr_stat_01_cvav_platform", titre: "Centre de statistiques exports multi niveaux scr stat 01 cvav platform", domaine: "Statistiques & Pilotage" },
  { slug: "certificat_de_conformit_archivistique_iso_19005_3_pdf_a_3b_acte_notari_canonique", titre: "Certificat de conformit archivistique iso 19005 3 pdf a 3b acte notari canonique", domaine: "Chancellerie & Bibliothèque" },
  { slug: "certificat_de_plein_air_camp_pascal_a4_imprimable_mo_se_assi_cvav_platform", titre: "Certificat de plein air camp pascal a4 imprimable mo se assi cvav platform", domaine: "Camps & Pèlerinages" },
  { slug: "certificat_notari_d_archivage_canonique_export_impression_pdf_a4_grand_camp", titre: "Certificat notari d archivage canonique export impression pdf a4 grand camp", domaine: "Camps & Pèlerinages" },
  { slug: "check_list_sanitaire_panier_repas_intendance_cuisine_sandrine_kanga", titre: "Check list sanitaire panier repas intendance cuisine sandrine kanga", domaine: "Finances & Cotisations" },
  { slug: "cl_ture_de_caisse_journali_re_des_esp_ces_scr_fin_01_cath_drale_christ_roi", titre: "Cl ture de caisse journali re des esp ces scr fin 01 cath drale christ roi", domaine: "Finances & Cotisations" },
  { slug: "cl_ture_de_l_margement_pv_officiel_patrouille_saint_joseph_25_28", titre: "Cl ture de l margement pv officiel patrouille saint joseph 25 28", domaine: "Terrain & Sécurité" },
  { slug: "cl_ture_de_l_margement_scellement_canonique_28_28", titre: "Cl ture de l margement scellement canonique 28 28", domaine: "Registres & Tabularium" },
  { slug: "cl_ture_g_n_rale_bilan_synoptique_grand_camp_pascal_yamoussoukro", titre: "Cl ture g n rale bilan synoptique grand camp pascal yamoussoukro", domaine: "Camps & Pèlerinages" },
  { slug: "cl_ture_officielle_scellement_canonique_du_trimestre_1_superadmin_dioc_se_de", titre: "Cl ture officielle scellement canonique du trimestre 1 superadmin dioc se de", domaine: "Registres & Tabularium" },
  { slug: "composition_flash_sms_push_parents_cvav_urgence", titre: "Composition flash sms push parents cvav urgence", domaine: "Terrain & Sécurité" },
  { slug: "confirmation_avenant_scell_d_cret_mis_jour_abb_jean_marc_koffi", titre: "Confirmation avenant scell d cret mis jour abb jean marc koffi", domaine: "Registres & Tabularium" },
  { slug: "confirmation_de_mise_jour_mon_compte_cvav_platform", titre: "Confirmation de mise jour mon compte cvav platform", domaine: "Administration & Référentiels" },
  { slug: "confirmation_enregistrement_scellement_canonique_act_pelerinage_enfants_cvav", titre: "Confirmation enregistrement scellement canonique act pelerinage enfants cvav", domaine: "Camps & Pèlerinages" },
  { slug: "confirmation_ex_cution_du_versement_de_la_subvention_p_r_quative_56_000_fcfa", titre: "Confirmation ex cution du versement de la subvention p r quative 56 000 fcfa", domaine: "Finances & Cotisations" },
  { slug: "confirmation_extension_d_canale_scell_e_d_cret_mis_jour_abb_jean_marc_koffi", titre: "Confirmation extension d canale scell e d cret mis jour abb jean marc koffi", domaine: "Registres & Tabularium" },
  { slug: "confirmation_mandat_mis_sms_2fa_d_livr_abb_charles_am_d_e_konan_wf_00", titre: "Confirmation mandat mis sms 2fa d livr abb charles am d e konan wf 00", domaine: "Gouvernance & Synodalité" },
  { slug: "confirmation_mandat_mis_sms_2fa_d_livr_abb_paul_marie_gnamien_wf_00", titre: "Confirmation mandat mis sms 2fa d livr abb paul marie gnamien wf 00", domaine: "Gouvernance & Synodalité" },
  { slug: "confirmation_mandat_mis_sms_2fa_d_livr_wf_00_superadmin_dioc_se_de_daloa", titre: "Confirmation mandat mis sms 2fa d livr wf 00 superadmin dioc se de daloa", domaine: "Gouvernance & Synodalité" },
  { slug: "confirmation_mot_de_passe_modifi_sms_tuteur_d_livr_mon_compte_cvav_platform", titre: "Confirmation mot de passe modifi sms tuteur d livr mon compte cvav platform", domaine: "Authentification" },
  { slug: "confirmation_notification_de_t_l_chargement_r_ussi_acte_notari_canonique", titre: "Confirmation notification de t l chargement r ussi acte notari canonique", domaine: "Espace Militant" },
  { slug: "confirmation_notification_de_t_l_chargement_r_ussi_quittance_piscopale_cath", titre: "Confirmation notification de t l chargement r ussi quittance piscopale cath", domaine: "Espace Militant" },
  { slug: "confirmation_pr_inscription_envoy_e_cvav_platform", titre: "Confirmation pr inscription envoy e cvav platform", domaine: "Portail & Inscriptions" },
  { slug: "confirmation_r_initialisation_redirection_tableau_de_bord_cvav_platform", titre: "Confirmation r initialisation redirection tableau de bord cvav platform", domaine: "Authentification" },
  { slug: "confirmation_r_vocation_des_sessions_nomades_scr_usr_02_sandrine_kanga", titre: "Confirmation r vocation des sessions nomades scr usr 02 sandrine kanga", domaine: "Authentification" },
  { slug: "confirmation_r_vocation_globale_des_sessions_journal_des_acc_s_mo_se_assi", titre: "Confirmation r vocation globale des sessions journal des acc s mo se assi", domaine: "Authentification" },
  { slug: "confirmation_rejet_notification_sms_d_livr_e_wf_03_admin_paroisse", titre: "Confirmation rejet notification sms d livr e wf 03 admin paroisse", domaine: "Espace Militant" },
  { slug: "confirmation_scellement_publication_de_document_san_biv_2025_02_cvav_platform", titre: "Confirmation scellement publication de document san biv 2025 02 cvav platform", domaine: "Registres & Tabularium" },
  { slug: "confirmation_t_l_chargement_r_ussi_bilan_financier_pdf_a_3b_p_lerinage_2025", titre: "Confirmation t l chargement r ussi bilan financier pdf a 3b p lerinage 2025", domaine: "Finances & Cotisations" },
  { slug: "confirmation_t_l_chargement_r_ussi_du_fichier_csv_registre_paroissial", titre: "Confirmation t l chargement r ussi du fichier csv registre paroissial", domaine: "Registres & Tabularium" },
  { slug: "confirmation_t_l_chargement_r_ussi_pack_7_ordres_de_mission_pdf_a_3b", titre: "Confirmation t l chargement r ussi pack 7 ordres de mission pdf a 3b", domaine: "Chancellerie & Bibliothèque" },
  { slug: "connexion_cvav_platform", titre: "Connexion cvav platform", domaine: "Authentification" },
  { slug: "connexion_pastorale_espace_chefs_dirigeants_cvav", titre: "Connexion pastorale espace chefs dirigeants cvav", domaine: "Authentification" },
  { slug: "console_d_approbation_d_livrance_des_cartes_cvav_platform", titre: "Console d approbation d livrance des cartes cvav platform", domaine: "Console Paroissiale" },
  { slug: "console_d_approbation_dossier_amenan_gr_ce_brou_validation_gravure_pvc", titre: "Console d approbation dossier amenan gr ce brou validation gravure pvc", domaine: "Console Paroissiale" },
  { slug: "console_d_approbation_dossier_david_konan_encaissement_validation", titre: "Console d approbation dossier david konan encaissement validation", domaine: "Console Paroissiale" },
  { slug: "console_d_approbation_dossier_jean_philippe_kanga_fiche_sant_manquante_1", titre: "Console d approbation dossier jean philippe kanga fiche sant manquante 1", domaine: "Console Paroissiale" },
  { slug: "console_d_approbation_dossier_jean_philippe_kanga_fiche_sant_manquante_2", titre: "Console d approbation dossier jean philippe kanga fiche sant manquante 2", domaine: "Console Paroissiale" },
  { slug: "console_d_approbation_dossier_marie_gr_ce_yao_cotisation_esp_ces", titre: "Console d approbation dossier marie gr ce yao cotisation esp ces", domaine: "Console Paroissiale" },
  { slug: "console_d_approbation_dossier_marie_gr_ce_yao_encaissement_esp_ces", titre: "Console d approbation dossier marie gr ce yao encaissement esp ces", domaine: "Console Paroissiale" },
  { slug: "console_d_approbation_dossier_suivant_ange_emmanuel_kouame", titre: "Console d approbation dossier suivant ange emmanuel kouame", domaine: "Console Paroissiale" },
  { slug: "console_d_approbation_encaissement_esp_ces_mo_se_koffi_assi", titre: "Console d approbation encaissement esp ces mo se koffi assi", domaine: "Console Paroissiale" },
  { slug: "console_d_approbation_guichet_d_encaissement_paroissial_cvav_platform", titre: "Console d approbation guichet d encaissement paroissial cvav platform", domaine: "Console Paroissiale" },
  { slug: "console_d_approbation_instruction_dossier_marc_aur_le_kouassi_8860", titre: "Console d approbation instruction dossier marc aur le kouassi 8860", domaine: "Console Paroissiale" },
  { slug: "console_d_approbation_r_gularisation_fiche_sant_sandrine_kanga_2", titre: "Console d approbation r gularisation fiche sant sandrine kanga 2", domaine: "Console Paroissiale" },
  { slug: "console_d_approbation_saisie_guichet_fiche_sant_dossier_jean_philippe_kanga_1", titre: "Console d approbation saisie guichet fiche sant dossier jean philippe kanga 1", domaine: "Console Paroissiale" },
  { slug: "console_d_approbation_saisie_guichet_fiche_sant_dossier_jean_philippe_kanga_2", titre: "Console d approbation saisie guichet fiche sant dossier jean philippe kanga 2", domaine: "Console Paroissiale" },
  { slug: "console_d_approbation_validation_des_dossiers_refonte_admin_chef", titre: "Console d approbation validation des dossiers refonte admin chef", domaine: "Console Paroissiale" },
  { slug: "console_d_approbation_validation_dossier_ordonnancement_carte_pvc_ange_emmanuel", titre: "Console d approbation validation dossier ordonnancement carte pvc ange emmanuel", domaine: "Console Paroissiale" },
  { slug: "console_d_instruction_berthe_marie_dje_rec_dal_2024_8853_admin_paroisse", titre: "Console d instruction berthe marie dje rec dal 2024 8853 admin paroisse", domaine: "Console Paroissiale" },
  { slug: "console_d_instruction_dossier_prioritaire_01_sandrine_kanga_rec_dal_2024_8854", titre: "Console d instruction dossier prioritaire 01 sandrine kanga rec dal 2024 8854", domaine: "Console Paroissiale" },
  { slug: "console_d_instruction_dossier_prioritaire_1_berthe_dje_rec_dal_2024_8853", titre: "Console d instruction dossier prioritaire 1 berthe dje rec dal 2024 8853", domaine: "Console Paroissiale" },
  { slug: "console_de_r_daction_diffusion_pastorale_scr_com_01_cvav_platform", titre: "Console de r daction diffusion pastorale scr com 01 cvav platform", domaine: "Console Paroissiale" },
  { slug: "console_de_sauvegarde_continuit_pastorale_scr_sys_bak_dioc_se_de_daloa", titre: "Console de sauvegarde continuit pastorale scr sys bak dioc se de daloa", domaine: "Console Paroissiale" },
  { slug: "console_dioc_saine_doyenn_super_admin_cvav_platform", titre: "Console dioc saine doyenn super admin cvav platform", domaine: "Console Paroissiale" },
  { slug: "consultation_d_archive_sanitaire_certificat_m_dical_de_jean_philippe_kanga", titre: "Consultation d archive sanitaire certificat m dical de jean philippe kanga", domaine: "Chancellerie & Bibliothèque" },
  { slug: "cr_ation_d_un_administrateur_paroissial_wf_00_5_6_cl_s_accord_es_superadmin", titre: "Cr ation d un administrateur paroissial wf 00 5 6 cl s accord es superadmin", domaine: "Gouvernance & Synodalité" },
  { slug: "cr_ation_d_un_administrateur_paroissial_wf_00_notre_dame_de_la_salette_d_issia", titre: "Cr ation d un administrateur paroissial wf 00 notre dame de la salette d issia", domaine: "Gouvernance & Synodalité" },
  { slug: "cr_ation_d_un_administrateur_paroissial_wf_00_sainte_th_r_se_de_bediala", titre: "Cr ation d un administrateur paroissial wf 00 sainte th r se de bediala", domaine: "Gouvernance & Synodalité" },
  { slug: "cr_ation_d_un_administrateur_paroissial_wf_00_superadmin_dioc_se_de_daloa", titre: "Cr ation d un administrateur paroissial wf 00 superadmin dioc se de daloa", domaine: "Gouvernance & Synodalité" },
  { slug: "d_cret_d_exeat_canonique_pdf_a_3b_ange_gabriel_traor_n_ex_2024_041", titre: "D cret d exeat canonique pdf a 3b ange gabriel traor n ex 2024 041", domaine: "Mutations & Exeat" },
  { slug: "d_cret_d_exeat_canonique_scell_mutation_valid_e_scr_mut_01_berthe_marie_dje", titre: "D cret d exeat canonique scell mutation valid e scr mut 01 berthe marie dje", domaine: "Registres & Tabularium" },
  { slug: "d_cret_d_investiture_pastorale_pdf_a_3b_abb_charles_am_d_e_konan_n_050_dal_2024", titre: "D cret d investiture pastorale pdf a 3b abb charles am d e konan n 050 dal 2024", domaine: "Pédagogie & Investiture" },
  { slug: "d_cret_piscopal_de_nomination_canonique_pdf_a_3b_mgr_alexis_touali_doyen_du", titre: "D cret piscopal de nomination canonique pdf a 3b mgr alexis touali doyen du", domaine: "Chancellerie & Bibliothèque" },
  { slug: "d_tail_financier_contribution_p_r_quative_doyenn_centre_daloa_ville", titre: "D tail financier contribution p r quative doyenn centre daloa ville", domaine: "Finances & Cotisations" },
  { slug: "d_tail_financier_p_r_quation_d_canale_doyenn_ouest_dioc_se_de_daloa", titre: "D tail financier p r quation d canale doyenn ouest dioc se de daloa", domaine: "Finances & Cotisations" },
  { slug: "dashboard_militant_espace_jeune_cvav_platform", titre: "Dashboard militant espace jeune cvav platform", domaine: "Espace Militant" },
  { slug: "diffusion_pastorale_d_p_che_piscopale_rappel_aux_48_cur_s_de_paroisse", titre: "Diffusion pastorale d p che piscopale rappel aux 48 cur s de paroisse", domaine: "Console Paroissiale" },
  { slug: "encaissement_confirm_carte_mise_marie_gr_ce_yao_console_admin", titre: "Encaissement confirm carte mise marie gr ce yao console admin", domaine: "Console Paroissiale" },
  { slug: "encaissement_d_une_cotisation_tardive_au_guichet_scr_act_01_grand_camp_pascal", titre: "Encaissement d une cotisation tardive au guichet scr act 01 grand camp pascal", domaine: "Finances & Cotisations" },
  { slug: "encaissement_esp_ces_r_ussi_carte_mise_marie_gr_ce_yao", titre: "Encaissement esp ces r ussi carte mise marie gr ce yao", domaine: "Finances & Cotisations" },
  { slug: "encaissement_valid_ordre_de_gravure_transmis_marc_aur_le_kouassi", titre: "Encaissement valid ordre de gravure transmis marc aur le kouassi", domaine: "Console Paroissiale" },
  { slug: "encaissement_valid_quittance_a4_imprimable_marie_gr_ce_yao", titre: "Encaissement valid quittance a4 imprimable marie gr ce yao", domaine: "Finances & Cotisations" },
  { slug: "encaissement_valid_quittance_a4_imprimable_mo_se_koffi_assi", titre: "Encaissement valid quittance a4 imprimable mo se koffi assi", domaine: "Finances & Cotisations" },
  { slug: "encaissement_valid_quittance_d_finitive_mise_emmanuel_koffi", titre: "Encaissement valid quittance d finitive mise emmanuel koffi", domaine: "Finances & Cotisations" },
  { slug: "extension_des_comp_tences_pastorales_doyenn_centre_abb_jean_marc_koffi", titre: "Extension des comp tences pastorales doyenn centre abb jean marc koffi", domaine: "Pédagogie & Investiture" },
  { slug: "feuille_d_margement_officielle_a4_patrouille_sainte_bernadette_notre_dame_de_la", titre: "Feuille d margement officielle a4 patrouille sainte bernadette notre dame de la", domaine: "Terrain & Sécurité" },
  { slug: "feuille_d_margement_officielle_a4_remise_carte_pvc_berthe_marie_dje", titre: "Feuille d margement officielle a4 remise carte pvc berthe marie dje", domaine: "Chancellerie & Bibliothèque" },
  { slug: "feuille_d_margement_officielle_a4_remise_des_cartes_pvc_lot_lot_2024_03", titre: "Feuille d margement officielle a4 remise des cartes pvc lot lot 2024 03", domaine: "Chancellerie & Bibliothèque" },
  { slug: "feuille_de_ban_compl_te_r_le_d_investiture_scr_cer_04_cath_drale_christ_roi", titre: "Feuille de ban compl te r le d investiture scr cer 04 cath drale christ roi", domaine: "Pédagogie & Investiture" },
  { slug: "feuille_de_surveillance_r_animation_p_diatrique_box_02_chr_yamoussoukro", titre: "Feuille de surveillance r animation p diatrique box 02 chr yamoussoukro", domaine: "Pédagogie & Investiture" },
  { slug: "fiche_administrative_d_taill_e_cath_drale_christ_roi_dioc_se_de_daloa", titre: "Fiche administrative d taill e cath drale christ roi dioc se de daloa", domaine: "Administration & Référentiels" },
  { slug: "fiche_administrative_d_taill_e_paroisse_notre_dame_de_la_salette_d_issia", titre: "Fiche administrative d taill e paroisse notre dame de la salette d issia", domaine: "Administration & Référentiels" },
  { slug: "fiche_administrative_d_taill_e_paroisse_saint_marc_de_tazibouo_daloa", titre: "Fiche administrative d taill e paroisse saint marc de tazibouo daloa", domaine: "Administration & Référentiels" },
  { slug: "fiche_consultation_m_dicale_terrain_dr._yao_camp_pascal", titre: "Fiche consultation m dicale terrain dr. yao camp pascal", domaine: "Terrain & Sécurité" },
  { slug: "fiche_d_taill_e_compl_te_militant_berthe_marie_dje_cvav_dal_2024_8853_a", titre: "Fiche d taill e compl te militant berthe marie dje cvav dal 2024 8853 a", domaine: "Espace Militant" },
  { slug: "fiche_d_taill_e_dossier_d_investiture_mo_se_koffi_assi_scr_cer_07_cath_drale", titre: "Fiche d taill e dossier d investiture mo se koffi assi scr cer 07 cath drale", domaine: "Pédagogie & Investiture" },
  { slug: "fiche_d_taill_e_mandataire_abb_charles_am_d_e_konan_superadmin", titre: "Fiche d taill e mandataire abb charles am d e konan superadmin", domaine: "Gouvernance & Synodalité" },
  { slug: "fiche_d_taill_e_mandataire_abb_jean_marc_koffi_superadmin", titre: "Fiche d taill e mandataire abb jean marc koffi superadmin", domaine: "Gouvernance & Synodalité" },
  { slug: "fiche_d_taill_e_mandataire_actualis_e_avenant_av_1_abb_jean_marc_koffi", titre: "Fiche d taill e mandataire actualis e avenant av 1 abb jean marc koffi", domaine: "Gouvernance & Synodalité" },
  { slug: "fiche_d_taill_e_militant_actualis_e_notre_dame_de_la_salette_d_issia_berthe", titre: "Fiche d taill e militant actualis e notre dame de la salette d issia berthe", domaine: "Espace Militant" },
  { slug: "fiche_d_taill_e_militant_amenan_gr_ce_brou_8845_a", titre: "Fiche d taill e militant amenan gr ce brou 8845 a", domaine: "Espace Militant" },
  { slug: "fiche_d_taill_e_militant_amenan_gr_ce_brou_carte_pvc_historique_des_scans", titre: "Fiche d taill e militant amenan gr ce brou carte pvc historique des scans", domaine: "Espace Militant" },
  { slug: "fiche_d_taill_e_militant_carte_suspendue_blacklist_e_amenan_gr_ce_brou", titre: "Fiche d taill e militant carte suspendue blacklist e amenan gr ce brou", domaine: "Espace Militant" },
  { slug: "fiche_d_taill_e_t_l_m_trie_casier_isotherme_04_sandrine_kanga", titre: "Fiche d taill e t l m trie casier isotherme 04 sandrine kanga", domaine: "Camps & Pèlerinages" },
  { slug: "fiche_de_consultation_m_dicale_export_impression_pdf_camp_pascal", titre: "Fiche de consultation m dicale export impression pdf camp pascal", domaine: "Camps & Pèlerinages" },
  { slug: "fiche_de_liaison_m_dicale_d_vacuation_chr_export_impression_pdf", titre: "Fiche de liaison m dicale d vacuation chr export impression pdf", domaine: "Statistiques & Pilotage" },
  { slug: "fiche_de_soin_terrain_sn_042_rapport_d_incident_pdf_a4_christian_ak", titre: "Fiche de soin terrain sn 042 rapport d incident pdf a4 christian ak", domaine: "Terrain & Sécurité" },
  { slug: "fiche_militant_historique_d_assiduit_scans_nfc_mo_se_assi_cvav_platform", titre: "Fiche militant historique d assiduit scans nfc mo se assi cvav platform", domaine: "Espace Militant" },
  { slug: "fiche_militant_lign_e_initiatique_brevets_scell_s_mo_se_assi_cvav_platform", titre: "Fiche militant lign e initiatique brevets scell s mo se assi cvav platform", domaine: "Espace Militant" },
  { slug: "fiche_militant_post_promotion_mo_se_koffi_assi_cvav_platform", titre: "Fiche militant post promotion mo se koffi assi cvav platform", domaine: "Espace Militant" },
  { slug: "fiche_paroissiale_actes_mandats_canoniques_8_actes_paroisse_saint_marc_de", titre: "Fiche paroissiale actes mandats canoniques 8 actes paroisse saint marc de", domaine: "Console Paroissiale" },
  { slug: "fiche_paroissiale_finances_cotisations_500_500_fcfa_cath_drale_christ_roi", titre: "Fiche paroissiale finances cotisations 500 500 fcfa cath drale christ roi", domaine: "Console Paroissiale" },
  { slug: "fiche_paroissiale_journal_filtr_par_canal_wave_ci_34_cath_drale_christ_roi", titre: "Fiche paroissiale journal filtr par canal wave ci 34 cath drale christ roi", domaine: "Console Paroissiale" },
  { slug: "fiche_paroissiale_quasi_paroisse_saint_paul_de_tagoura_zone_rurale", titre: "Fiche paroissiale quasi paroisse saint paul de tagoura zone rurale", domaine: "Console Paroissiale" },
  { slug: "fiche_paroissiale_sections_effectifs_132_paroisse_saint_marc_de_tazibouo", titre: "Fiche paroissiale sections effectifs 132 paroisse saint marc de tazibouo", domaine: "Console Paroissiale" },
  { slug: "fiche_paroissiale_sections_effectifs_143_cath_drale_christ_roi", titre: "Fiche paroissiale sections effectifs 143 cath drale christ roi", domaine: "Console Paroissiale" },
  { slug: "fiche_r_capitulative_cuisine_bivouacs_s_curit_alimentaire_sandrine_kanga", titre: "Fiche r capitulative cuisine bivouacs s curit alimentaire sandrine kanga", domaine: "Camps & Pèlerinages" },
  { slug: "fiche_sanitaire_a4_d_taill_e_aptitude_m_dicale_ange_emmanuel_kouame", titre: "Fiche sanitaire a4 d taill e aptitude m dicale ange emmanuel kouame", domaine: "Assainissement" },
  { slug: "fiche_sant_sanitaire_cvav_platform", titre: "Fiche sant sanitaire cvav platform", domaine: "Assainissement" },
  { slug: "file_d_attente_fifo_actualis_e_10_dossiers_restants_cath_drale_christ_roi", titre: "File d attente fifo actualis e 10 dossiers restants cath drale christ roi", domaine: "Console Paroissiale" },
  { slug: "file_d_attente_fifo_actualis_e_11_dossiers_restants_cath_drale_christ_roi", titre: "File d attente fifo actualis e 11 dossiers restants cath drale christ roi", domaine: "Console Paroissiale" },
  { slug: "file_d_attente_fifo_compl_te_12_dossiers_cath_drale_christ_roi", titre: "File d attente fifo compl te 12 dossiers cath drale christ roi", domaine: "Console Paroissiale" },
  { slug: "file_des_dossiers_d_adh_sion_en_attente_12_restants_cath_drale_christ_roi", titre: "File des dossiers d adh sion en attente 12 restants cath drale christ roi", domaine: "Console Paroissiale" },
  { slug: "file_des_dossiers_d_adh_sion_en_attente_13_restants_cath_drale_christ_roi", titre: "File des dossiers d adh sion en attente 13 restants cath drale christ roi", domaine: "Console Paroissiale" },
  { slug: "file_des_dossiers_d_adh_sion_en_attente_console_d_approbation_paroissiale", titre: "File des dossiers d adh sion en attente console d approbation paroissiale", domaine: "Console Paroissiale" },
  { slug: "gestion_d_taill_e_des_camps_rassemblements_dioc_sains_cvav_platform", titre: "Gestion d taill e des camps rassemblements dioc sains cvav platform", domaine: "Camps & Pèlerinages" },
  { slug: "gestion_de_mon_quipe_scr_ped_02_patrouille_saint_joseph_cadets", titre: "Gestion de mon quipe scr ped 02 patrouille saint joseph cadets", domaine: "Terrain & Sécurité" },
  { slug: "gestion_de_mon_quipe_scr_ped_02_tableau_analytique_des_12_militants", titre: "Gestion de mon quipe scr ped 02 tableau analytique des 12 militants", domaine: "Espace Militant" },
  { slug: "gestion_des_cotisations_tr_sorerie_paroissiale_scr_fin_01_cath_drale_christ_roi", titre: "Gestion des cotisations tr sorerie paroissiale scr fin 01 cath drale christ roi", domaine: "Console Paroissiale" },
  { slug: "gestion_des_doyenn_s_organisation_dioc_saine_superadmin_dioc_se_de_daloa", titre: "Gestion des doyenn s organisation dioc saine superadmin dioc se de daloa", domaine: "Administration & Référentiels" },
  { slug: "gestion_des_mandats_nominations_fonctions_pastorales_scr_gov_02_cvav_platform", titre: "Gestion des mandats nominations fonctions pastorales scr gov 02 cvav platform", domaine: "Gouvernance & Synodalité" },
  { slug: "grand_livre_paroissial_d_archivage_canonique_export_impression_pdf_a_3b_cath_1", titre: "Grand livre paroissial d archivage canonique export impression pdf a 3b cath 1", domaine: "Registres & Tabularium" },
  { slug: "grand_livre_paroissial_d_archivage_canonique_export_impression_pdf_a_3b_cath_2", titre: "Grand livre paroissial d archivage canonique export impression pdf a 3b cath 2", domaine: "Registres & Tabularium" },
  { slug: "grand_r_pertoire_dioc_sain_des_1_842_militants_exercice_2025_2026_cvav_platform", titre: "Grand r pertoire dioc sain des 1 842 militants exercice 2025 2026 cvav platform", domaine: "Espace Militant" },
  { slug: "grand_registre_paroissial_consolid_14_brevets_scell_s_cath_drale_christ_roi", titre: "Grand registre paroissial consolid 14 brevets scell s cath drale christ roi", domaine: "Pédagogie & Investiture" },
  { slug: "gravure_group_e_des_3_cartes_pvc_en_cours_badgeuse_evolis_cath_drale_christ_roi", titre: "Gravure group e des 3 cartes pvc en cours badgeuse evolis cath drale christ roi", domaine: "Pédagogie & Investiture" },
  { slug: "guichet_tr_sorerie_r_gularisation_encaissement_1_500_fcfa_emmanuel_koffi", titre: "Guichet tr sorerie r gularisation encaissement 1 500 fcfa emmanuel koffi", domaine: "Finances & Cotisations" },
  { slug: "guidage_azimut_balise_4_finale_le_sanctuaire", titre: "Guidage azimut balise 4 finale le sanctuaire", domaine: "Camps & Pèlerinages" },
  { slug: "historique_de_grade_lign_e_initiatique_scr_ped_03_mo_se_koffi_assi", titre: "Historique de grade lign e initiatique scr ped 03 mo se koffi assi", domaine: "Pédagogie & Investiture" },
  { slug: "historique_des_pr_sences_espace_jeune_cvav_platform", titre: "Historique des pr sences espace jeune cvav platform", domaine: "Espace Militant" },
  { slug: "infirmerie_camp_pascal_modale_consigner_un_soin_consultation_m_dicale", titre: "Infirmerie camp pascal modale consigner un soin consultation m dicale", domaine: "Camps & Pèlerinages" },
  { slug: "infirmerie_fiches_sanitaires_grand_camp_pascal_yamoussoukro", titre: "Infirmerie fiches sanitaires grand camp pascal yamoussoukro", domaine: "Camps & Pèlerinages" },
  { slug: "infirmerie_fiches_sanitaires_vacuation_r_ussie_d_ange_emmanuel", titre: "Infirmerie fiches sanitaires vacuation r ussie d ange emmanuel", domaine: "Assainissement" },
  { slug: "inspecteur_xml_brut_01_registre_sanitaire_vigilances.xml_lecteur_pdf_a", titre: "Inspecteur xml brut 01 registre sanitaire vigilances.xml lecteur pdf a", domaine: "Registres & Tabularium" },
  { slug: "inspecteur_xml_signature_xml_dsig_lecteur_pdf_a", titre: "Inspecteur xml signature xml dsig lecteur pdf a", domaine: "Chancellerie & Bibliothèque" },
  { slug: "inspection_cryptographique_des_signatures_num_riques_x.509_pades_grand_livre", titre: "Inspection cryptographique des signatures num riques x.509 pades grand livre", domaine: "Chancellerie & Bibliothèque" },
  { slug: "inspection_cryptographique_des_signatures_x.509_pades_ltv_grand_livre_paroissial", titre: "Inspection cryptographique des signatures x.509 pades ltv grand livre paroissial", domaine: "Chancellerie & Bibliothèque" },
  { slug: "inspection_cryptographique_sha_256_certificats_document_mo_se_assi", titre: "Inspection cryptographique sha 256 certificats document mo se assi", domaine: "Chancellerie & Bibliothèque" },
  { slug: "inspection_de_l_acte_au_tabularium_dioc_sain_tab_dal_2025_av02_abb_jean_marc", titre: "Inspection de l acte au tabularium dioc sain tab dal 2025 av02 abb jean marc", domaine: "Registres & Tabularium" },
  { slug: "inspection_des_certificats_x.509_signature_num_rique_pv_patrouille_saint_joseph", titre: "Inspection des certificats x.509 signature num rique pv patrouille saint joseph", domaine: "Terrain & Sécurité" },
  { slug: "inspection_des_signatures_num_riques_x.509_pades_acte_notari_canonique", titre: "Inspection des signatures num riques x.509 pades acte notari canonique", domaine: "Chancellerie & Bibliothèque" },
  { slug: "inspection_signature_x.509_certificat_curie_d_issia_abb_paul_marie_gnamien", titre: "Inspection signature x.509 certificat curie d issia abb paul marie gnamien", domaine: "Chancellerie & Bibliothèque" },
  { slug: "inspection_signature_x.509_cha_ne_de_confiance_certificat_bak_2025_0815_full", titre: "Inspection signature x.509 cha ne de confiance certificat bak 2025 0815 full", domaine: "Chancellerie & Bibliothèque" },
  { slug: "instantan_synodal_scell_avec_succ_s_bak_2025_0815_full_dioc_se_de_daloa", titre: "Instantan synodal scell avec succ s bak 2025 0815 full dioc se de daloa", domaine: "Gouvernance & Synodalité" },
  { slug: "inventaire_complet_des_48_grands_livres_paroissiaux_d_pos_s_tabularium_dioc", titre: "Inventaire complet des 48 grands livres paroissiaux d pos s tabularium dioc", domaine: "Registres & Tabularium" },
  { slug: "inventaire_filtr_doyenn_ouest_zoukougbeu_tabularium_dioc_sain", titre: "Inventaire filtr doyenn ouest zoukougbeu tabularium dioc sain", domaine: "Registres & Tabularium" },
  { slug: "journal_d_audit_complet_des_145_actes_abb_jean_marc_koffi_cath_drale_christ_roi", titre: "Journal d audit complet des 145 actes abb jean marc koffi cath drale christ roi", domaine: "Administration & Référentiels" },
  { slug: "journal_d_audit_s_curit_officiel_a4.pdf_mo_se_assi", titre: "Journal d audit s curit officiel a4.pdf mo se assi", domaine: "Terrain & Sécurité" },
  { slug: "journal_d_encodage_nfc_mifare_1k_puce_badgeuse_evolis_primacy_2", titre: "Journal d encodage nfc mifare 1k puce badgeuse evolis primacy 2", domaine: "Terrain & Sécurité" },
  { slug: "journal_d_encodage_rfid_mifare_1k_ange_emmanuel_kouame", titre: "Journal d encodage rfid mifare 1k ange emmanuel kouame", domaine: "Terrain & Sécurité" },
  { slug: "journal_de_t_l_m_trie_des_14_casiers_isothermes_camp_pascal_2025", titre: "Journal de t l m trie des 14 casiers isothermes camp pascal 2025", domaine: "Espace Militant" },
  { slug: "journal_des_acc_s_sessions_actives_mo_se_assi_cvav_platform", titre: "Journal des acc s sessions actives mo se assi cvav platform", domaine: "Authentification" },
  { slug: "journal_des_d_p_ts_au_tabularium_dioc_sain_curie_piscopale_de_daloa", titre: "Journal des d p ts au tabularium dioc sain curie piscopale de daloa", domaine: "Registres & Tabularium" },
  { slug: "journal_des_d_p_ts_au_tabularium_doyenn_centre_filtr_42_actes", titre: "Journal des d p ts au tabularium doyenn centre filtr 42 actes", domaine: "Registres & Tabularium" },
  { slug: "landing_page_publique_cv_av_dioc_se_de_daloa_1", titre: "Landing page publique cv av dioc se de daloa 1", domaine: "Portail & Inscriptions" },
  { slug: "landing_page_publique_cv_av_dioc_se_de_daloa_2", titre: "Landing page publique cv av dioc se de daloa 2", domaine: "Portail & Inscriptions" },
  { slug: "landing_page_publique_refonte_desktop_tablette_cvav_daloa", titre: "Landing page publique refonte desktop tablette cvav daloa", domaine: "Portail & Inscriptions" },
  { slug: "landing_page_publique_refonte_mobile_cvav_daloa", titre: "Landing page publique refonte mobile cvav daloa", domaine: "Portail & Inscriptions" },
  { slug: "lecteur_pdf_a_natif_int_gr_consultation_audit_de_l_acte_notari_canonique", titre: "Lecteur pdf a natif int gr consultation audit de l acte notari canonique", domaine: "Chancellerie & Bibliothèque" },
  { slug: "lecteur_pdf_a_volet_pi_ces_jointes_xml_6_embarqu_es", titre: "Lecteur pdf a volet pi ces jointes xml 6 embarqu es", domaine: "Chancellerie & Bibliothèque" },
  { slug: "lev_e_de_suspension_r_ussie_pr_sence_valid_e_amenan_gr_ce_brou", titre: "Lev e de suspension r ussie pr sence valid e amenan gr ce brou", domaine: "Console Paroissiale" },
  { slug: "lot_de_14_brevets_scell_sign_avec_succ_s_scr_cer_06_cath_drale_christ_roi", titre: "Lot de 14 brevets scell sign avec succ s scr cer 06 cath drale christ roi", domaine: "Pédagogie & Investiture" },
  { slug: "mandats_canoniques_des_doyens_vicaires_d_canaux_superadmin_dioc_se_de_daloa", titre: "Mandats canoniques des doyens vicaires d canaux superadmin dioc se de daloa", domaine: "Gouvernance & Synodalité" },
  { slug: "mes_attestations_espace_jeune_cvav_platform", titre: "Mes attestations espace jeune cvav platform", domaine: "Espace Militant" },
  { slug: "mes_cotisations_quittances_espace_jeune_cvav_platform", titre: "Mes cotisations quittances espace jeune cvav platform", domaine: "Espace Militant" },
  { slug: "mission_des_brevets_scell_s_x.509_scr_cer_06_cath_drale_christ_roi", titre: "Mission des brevets scell s x.509 scr cer 06 cath drale christ roi", domaine: "Pédagogie & Investiture" },
  { slug: "modale_changer_le_mot_de_passe_mon_compte_cvav_platform", titre: "Modale changer le mot de passe mon compte cvav platform", domaine: "Authentification" },
  { slug: "modale_cr_er_un_administrateur_wf_00_superadmin_dioc_se_de_daloa", titre: "Modale cr er un administrateur wf 00 superadmin dioc se de daloa", domaine: "Gouvernance & Synodalité" },
  { slug: "modale_cr_er_une_nouvelle_patrouille_scr_gov_03_cath_drale_christ_roi", titre: "Modale cr er une nouvelle patrouille scr gov 03 cath drale christ roi", domaine: "Gouvernance & Synodalité" },
  { slug: "modale_d_affectation_des_militants_scr_gov_03_patrouille_saint_paul", titre: "Modale d affectation des militants scr gov 03 patrouille saint paul", domaine: "Espace Militant" },
  { slug: "modale_d_encaissement_au_guichet_scr_fin_01_cath_drale_christ_roi", titre: "Modale d encaissement au guichet scr fin 01 cath drale christ roi", domaine: "Finances & Cotisations" },
  { slug: "modale_de_rejet_avec_motif_obligatoire_wf_03_admin_paroisse", titre: "Modale de rejet avec motif obligatoire wf 03 admin paroisse", domaine: "Gouvernance & Synodalité" },
  { slug: "modale_de_suspension_canonique_de_compte_scr_sec_01_cvav_platform", titre: "Modale de suspension canonique de compte scr sec 01 cvav platform", domaine: "Console Paroissiale" },
  { slug: "modale_de_suspension_temporaire_de_la_carte_pvc_perte_signal_e_amenan_gr_ce_brou", titre: "Modale de suspension temporaire de la carte pvc perte signal e amenan gr ce brou", domaine: "Console Paroissiale" },
  { slug: "modale_modifier_les_habilitations_abb_jean_marc_koffi_superadmin", titre: "Modale modifier les habilitations abb jean marc koffi superadmin", domaine: "Administration & Référentiels" },
  { slug: "modale_modifier_mes_informations_mon_compte_cvav_platform", titre: "Modale modifier mes informations mon compte cvav platform", domaine: "Espace Militant" },
  { slug: "modale_t_l_verser_sceller_un_document_scr_doc_01_cvav_platform", titre: "Modale t l verser sceller un document scr doc 01 cvav platform", domaine: "Registres & Tabularium" },
  { slug: "module_terrain_activit_en_cours_patrouille_saint_joseph", titre: "Module terrain activit en cours patrouille saint joseph", domaine: "Terrain & Sécurité" },
  { slug: "mon_compte_profil_militant_espace_jeune_cvav_platform", titre: "Mon compte profil militant espace jeune cvav platform", domaine: "Espace Militant" },
  { slug: "mon_profil_fiche_sanitaire_pai_scr_usr_01_sandrine_kanga", titre: "Mon profil fiche sanitaire pai scr usr 01 sandrine kanga", domaine: "Espace Militant" },
  { slug: "mon_profil_identit_pastorale_scr_usr_01_sandrine_kanga", titre: "Mon profil identit pastorale scr usr 01 sandrine kanga", domaine: "Espace Militant" },
  { slug: "mon_profil_lign_e_p_dagogique_grades_scr_usr_01_sandrine_kanga", titre: "Mon profil lign e p dagogique grades scr usr 01 sandrine kanga", domaine: "Espace Militant" },
  { slug: "mot_de_passe_oubli_r_initialisation_cvav_platform", titre: "Mot de passe oubli r initialisation cvav platform", domaine: "Authentification" },
  { slug: "notification_directe_terrain_lev_e_de_r_serve_emmanuel_koffi", titre: "Notification directe terrain lev e de r serve emmanuel koffi", domaine: "Espace Militant" },
  { slug: "notification_push_t_l_relais_parents_aum_nerie_cvav_urgence", titre: "Notification push t l relais parents aum nerie cvav urgence", domaine: "Espace Militant" },
  { slug: "notification_sms_group_e_d_livr_e_3_3_tuteurs_retrait_cartes_pvc_cath_drale", titre: "Notification sms group e d livr e 3 3 tuteurs retrait cartes pvc cath drale", domaine: "Espace Militant" },
  { slug: "nouvelle_demande_d_attestation_scr_cer_01_mo_se_assi", titre: "Nouvelle demande d attestation scr cer 01 mo se assi", domaine: "Chancellerie & Bibliothèque" },
  { slug: "ordre_de_mission_a4_individuel_pdf_a_3b_barth_l_my_kouadio", titre: "Ordre de mission a4 individuel pdf a 3b barth l my kouadio", domaine: "Chancellerie & Bibliothèque" },
  { slug: "organisation_d_un_camp_rassemblement_scr_act_01_grand_camp_pascal_2025", titre: "Organisation d un camp rassemblement scr act 01 grand camp pascal 2025", domaine: "Camps & Pèlerinages" },
  { slug: "organisation_d_un_camp_rassemblement_scr_act_01_onglet_bivouacs_logistique", titre: "Organisation d un camp rassemblement scr act 01 onglet bivouacs logistique", domaine: "Camps & Pèlerinages" },
  { slug: "organisation_d_un_camp_rassemblement_scr_act_01_onglet_budget_actualis_313", titre: "Organisation d un camp rassemblement scr act 01 onglet budget actualis 313", domaine: "Finances & Cotisations" },
  { slug: "organisation_d_un_camp_rassemblement_scr_act_01_onglet_budget_cotisations", titre: "Organisation d un camp rassemblement scr act 01 onglet budget cotisations", domaine: "Finances & Cotisations" },
  { slug: "organisation_d_un_camp_rassemblement_scr_act_01_onglet_encadrement_quotas_d", titre: "Organisation d un camp rassemblement scr act 01 onglet encadrement quotas d", domaine: "Camps & Pèlerinages" },
  { slug: "organisation_d_un_camp_rassemblement_scr_act_01_onglet_param_tres_identit_du", titre: "Organisation d un camp rassemblement scr act 01 onglet param tres identit du", domaine: "Camps & Pèlerinages" },
  { slug: "organisation_d_un_camp_rassemblement_scr_act_01_registre_des_patrouilles_tentes", titre: "Organisation d un camp rassemblement scr act 01 registre des patrouilles tentes", domaine: "Terrain & Sécurité" },
  { slug: "palmar_s_cl_ture_du_jeu_grand_camp_daloa", titre: "Palmar s cl ture du jeu grand camp daloa", domaine: "Camps & Pèlerinages" },
  { slug: "param_tres_dioc_sains_chancellerie_scr_adm_01_cvav_platform", titre: "Param tres dioc sains chancellerie scr adm 01 cvav platform", domaine: "Chancellerie & Bibliothèque" },
  { slug: "param_tres_du_compte_s_curit_pastorale_scr_usr_02_sandrine_kanga", titre: "Param tres du compte s curit pastorale scr usr 02 sandrine kanga", domaine: "Terrain & Sécurité" },
  { slug: "planche_d_impression_officielle_des_14_billets_d_investiture_a4_d_coupable_cath", titre: "Planche d impression officielle des 14 billets d investiture a4 d coupable cath", domaine: "Pédagogie & Investiture" },
  { slug: "planche_d_impression_pdf_hd_a4_carte_officielle_jean_philippe_kanga", titre: "Planche d impression pdf hd a4 carte officielle jean philippe kanga", domaine: "Chancellerie & Bibliothèque" },
  { slug: "planification_session_d_investiture_de_pentec_te_scr_cer_04_cath_drale_christ", titre: "Planification session d investiture de pentec te scr cer 04 cath drale christ", domaine: "Authentification" },
  { slug: "planification_session_dioc_saine_p_lerinage_des_enfants_2025_act_pelerinage", titre: "Planification session dioc saine p lerinage des enfants 2025 act pelerinage", domaine: "Authentification" },
  { slug: "pointage_cam_ra_qr_scan_r_ussi_fiche_militant_david_konan", titre: "Pointage cam ra qr scan r ussi fiche militant david konan", domaine: "Espace Militant" },
  { slug: "pointage_nfc_terrain_admis_sous_r_serve_alerte_tr_sorier_emmanuel_koffi", titre: "Pointage nfc terrain admis sous r serve alerte tr sorier emmanuel koffi", domaine: "Finances & Cotisations" },
  { slug: "pointage_nfc_terrain_alerte_retard_assurance_emmanuel_koffi", titre: "Pointage nfc terrain alerte retard assurance emmanuel koffi", domaine: "Terrain & Sécurité" },
  { slug: "pointage_nfc_terrain_arriv_e_16_00_scan_r_ussi_ange_emmanuel_kouame", titre: "Pointage nfc terrain arriv e 16 00 scan r ussi ange emmanuel kouame", domaine: "Terrain & Sécurité" },
  { slug: "pointage_nfc_terrain_pr_sence_enregistr_e_jean_philippe_kanga", titre: "Pointage nfc terrain pr sence enregistr e jean philippe kanga", domaine: "Terrain & Sécurité" },
  { slug: "pointage_nfc_terrain_premier_rassemblement_issia_badge_ota_berthe_marie_dje", titre: "Pointage nfc terrain premier rassemblement issia badge ota berthe marie dje", domaine: "Terrain & Sécurité" },
  { slug: "pointage_nfc_terrain_scan_final_28_28_r_ussi_mo_se_assi", titre: "Pointage nfc terrain scan final 28 28 r ussi mo se assi", domaine: "Terrain & Sécurité" },
  { slug: "pointage_nfc_terrain_scan_r_ussi_27_28_david_konan", titre: "Pointage nfc terrain scan r ussi 27 28 david konan", domaine: "Terrain & Sécurité" },
  { slug: "pointage_nfc_terrain_scan_r_ussi_carte_jean_philippe_kanga", titre: "Pointage nfc terrain scan r ussi carte jean philippe kanga", domaine: "Terrain & Sécurité" },
  { slug: "pointage_qr_contr_le_d_assiduit_terrain_cvav", titre: "Pointage qr contr le d assiduit terrain cvav", domaine: "Terrain & Sécurité" },
  { slug: "pointage_rassemblement_margement_actualis_26_28_pr_sents", titre: "Pointage rassemblement margement actualis 26 28 pr sents", domaine: "Terrain & Sécurité" },
  { slug: "pointage_rassemblement_margement_actualis_patrouille_saint_joseph", titre: "Pointage rassemblement margement actualis patrouille saint joseph", domaine: "Terrain & Sécurité" },
  { slug: "pointage_rassemblement_pr_sence_confirm_e_25_28", titre: "Pointage rassemblement pr sence confirm e 25 28", domaine: "Terrain & Sécurité" },
  { slug: "pointage_terrain_basculement_automatique_nfc_cam_ra", titre: "Pointage terrain basculement automatique nfc cam ra", domaine: "Terrain & Sécurité" },
  { slug: "pointage_terrain_tentative_de_scan_carte_suspendue_refus_d_authentification", titre: "Pointage terrain tentative de scan carte suspendue refus d authentification", domaine: "Authentification" },
  { slug: "pr_inscription_desktop_confirmation_accus_de_r_ception", titre: "Pr inscription desktop confirmation accus de r ception", domaine: "Portail & Inscriptions" },
  { slug: "pr_inscription_desktop_tape_1_identit_qui_es_tu", titre: "Pr inscription desktop tape 1 identit qui es tu", domaine: "Portail & Inscriptions" },
  { slug: "pr_inscription_desktop_tape_2_coordonn_es_comment_te_joindre", titre: "Pr inscription desktop tape 2 coordonn es comment te joindre", domaine: "Portail & Inscriptions" },
  { slug: "pr_inscription_desktop_tape_3_paroisse_souhait_e_o_rejoindre", titre: "Pr inscription desktop tape 3 paroisse souhait e o rejoindre", domaine: "Portail & Inscriptions" },
  { slug: "pr_inscription_militant_cvav_platform", titre: "Pr inscription militant cvav platform", domaine: "Portail & Inscriptions" },
  { slug: "pr_inscription_militant_tape_1_identit_paroisse_dioc_se_de_daloa", titre: "Pr inscription militant tape 1 identit paroisse dioc se de daloa", domaine: "Portail & Inscriptions" },
  { slug: "pr_inscription_militant_tape_2_fiche_sant_liaison_dioc_se_de_daloa", titre: "Pr inscription militant tape 2 fiche sant liaison dioc se de daloa", domaine: "Portail & Inscriptions" },
  { slug: "pr_inscription_militant_tape_3_validation_cotisation_dioc_se_de_daloa", titre: "Pr inscription militant tape 3 validation cotisation dioc se de daloa", domaine: "Portail & Inscriptions" },
  { slug: "pr_inscription_tape_1_identit_cvav_platform", titre: "Pr inscription tape 1 identit cvav platform", domaine: "Portail & Inscriptions" },
  { slug: "pr_inscription_tape_1_identit_desktop_tablette", titre: "Pr inscription tape 1 identit desktop tablette", domaine: "Portail & Inscriptions" },
  { slug: "pr_inscription_tape_2_coordonn_es_cvav_platform", titre: "Pr inscription tape 2 coordonn es cvav platform", domaine: "Portail & Inscriptions" },
  { slug: "pr_inscription_tape_2_coordonn_es_tuteur_desktop_tablette", titre: "Pr inscription tape 2 coordonn es tuteur desktop tablette", domaine: "Portail & Inscriptions" },
  { slug: "pr_inscription_tape_3_paroisse_refonte_mobile", titre: "Pr inscription tape 3 paroisse refonte mobile", domaine: "Portail & Inscriptions" },
  { slug: "pr_inscription_tape_3_paroisse_souhait_e_cvav_platform", titre: "Pr inscription tape 3 paroisse souhait e cvav platform", domaine: "Portail & Inscriptions" },
  { slug: "pr_inscription_tape_3_paroisse_validation_desktop_tablette", titre: "Pr inscription tape 3 paroisse validation desktop tablette", domaine: "Portail & Inscriptions" },
  { slug: "pr_visualisation_brevet_scell_sandrine_kanga_scr_cer_06_cath_drale_christ_roi", titre: "Pr visualisation brevet scell sandrine kanga scr cer 06 cath drale christ roi", domaine: "Camps & Pèlerinages" },
  { slug: "proc_dure_d_vacuation_m_dicale_d_urgence_chr_yamoussoukro", titre: "Proc dure d vacuation m dicale d urgence chr yamoussoukro", domaine: "Terrain & Sécurité" },
  { slug: "proc_dure_de_mutation_paroissiale_d_cret_d_exeat_canonique_scr_mut_01_berthe", titre: "Proc dure de mutation paroissiale d cret d exeat canonique scr mut 01 berthe", domaine: "Console Paroissiale" },
  { slug: "proc_dure_de_mutation_paroissiale_exeat_canonique_scr_mut_01_berthe_marie_dje", titre: "Proc dure de mutation paroissiale exeat canonique scr mut 01 berthe marie dje", domaine: "Console Paroissiale" },
  { slug: "proc_s_verbal_de_cl_ture_scell_sign_scr_fin_01_cath_drale_christ_roi", titre: "Proc s verbal de cl ture scell sign scr fin 01 cath drale christ roi", domaine: "Registres & Tabularium" },
  { slug: "proc_s_verbal_scell_pdf_a_3b_patrouille_saint_joseph_28_28_pr_sents", titre: "Proc s verbal scell pdf a 3b patrouille saint joseph 28 28 pr sents", domaine: "Terrain & Sécurité" },
  { slug: "proc_s_verbal_scell_pdf_a_rassemblement_patrouille_saint_joseph_25_28", titre: "Proc s verbal scell pdf a rassemblement patrouille saint joseph 25 28", domaine: "Terrain & Sécurité" },
  { slug: "promotion_canonique_passage_militant_chef_scr_gov_01_barth_l_my_kouadio", titre: "Promotion canonique passage militant chef scr gov 01 barth l my kouadio", domaine: "Espace Militant" },
  { slug: "promulgation_solennelle_ouverture_des_inscriptions_p_lerinage_des_enfants_2025", titre: "Promulgation solennelle ouverture des inscriptions p lerinage des enfants 2025", domaine: "Portail & Inscriptions" },
  { slug: "protocole_pai_d_taill_urgence_anaphylaxie_sandrine_kanga_med_2025_082_dl", titre: "Protocole pai d taill urgence anaphylaxie sandrine kanga med 2025 082 dl", domaine: "Terrain & Sécurité" },
  { slug: "quittance_officielle_a4_imprimable_mo_se_assi_adh_sion_pastorale_2024_2025", titre: "Quittance officielle a4 imprimable mo se assi adh sion pastorale 2024 2025", domaine: "Finances & Cotisations" },
  { slug: "quittance_officielle_a4_imprimable_quit_2024_0145_franck_ric_koffi", titre: "Quittance officielle a4 imprimable quit 2024 0145 franck ric koffi", domaine: "Finances & Cotisations" },
  { slug: "quittance_piscopale_dioc_saine_a4.pdf_cath_drale_christ_roi_500_500_fcfa", titre: "Quittance piscopale dioc saine a4.pdf cath drale christ roi 500 500 fcfa", domaine: "Finances & Cotisations" },
  { slug: "r_initialisation_du_mot_de_passe_tape_2_code_otp_nouveau_mot_de_passe_cvav", titre: "R initialisation du mot de passe tape 2 code otp nouveau mot de passe cvav", domaine: "Authentification" },
  { slug: "r_pertoire_des_utilisateurs_et_administrateurs_paroissiaux_superadmin_dioc_se", titre: "R pertoire des utilisateurs et administrateurs paroissiaux superadmin dioc se", domaine: "Administration & Référentiels" },
  { slug: "r_pertoire_hi_rarchique_tabulaire_des_48_paroisses_superadmin_dioc_se_de_daloa", titre: "R pertoire hi rarchique tabulaire des 48 paroisses superadmin dioc se de daloa", domaine: "Administration & Référentiels" },
  { slug: "rapport_d_incident_sanitaire_export_impression_pdf_a4_commission_dioc_saine", titre: "Rapport d incident sanitaire export impression pdf a4 commission dioc saine", domaine: "Terrain & Sécurité" },
  { slug: "rapport_d_incident_sanitaire_synth_se_m_dico_l_gale_commission_dioc_saine", titre: "Rapport d incident sanitaire synth se m dico l gale commission dioc saine", domaine: "Terrain & Sécurité" },
  { slug: "re_u_de_caisse_provisoire_a4_dossier_marc_aur_le_kouassi_patrice_kouassi", titre: "Re u de caisse provisoire a4 dossier marc aur le kouassi patrice kouassi", domaine: "Finances & Cotisations" },
  { slug: "re_u_de_r_gularisation_guichet_bordereau_sanitaire_a4_jean_philippe_kanga", titre: "Re u de r gularisation guichet bordereau sanitaire a4 jean philippe kanga", domaine: "Assainissement" },
  { slug: "re_u_provisoire_d_admission_sous_r_serve_emmanuel_koffi", titre: "Re u provisoire d admission sous r serve emmanuel koffi", domaine: "Portail & Inscriptions" },
  { slug: "registre_consolid_des_demandes_d_attestation_scr_cer_03_scr_cer_02_liste_cath", titre: "Registre consolid des demandes d attestation scr cer 03 scr cer 02 liste cath", domaine: "Registres & Tabularium" },
  { slug: "registre_consolid_des_paniers_repas_contr_l_s_intendance_restauration_camp", titre: "Registre consolid des paniers repas contr l s intendance restauration camp", domaine: "Finances & Cotisations" },
  { slug: "registre_d_admission_sau_dossier_d_choquage_chr_yamoussoukro", titre: "Registre d admission sau dossier d choquage chr yamoussoukro", domaine: "Portail & Inscriptions" },
  { slug: "registre_des_militants_notre_dame_de_la_salette_d_issia_98_inscrits_berthe_dje", titre: "Registre des militants notre dame de la salette d issia 98 inscrits berthe dje", domaine: "Espace Militant" },
  { slug: "registre_dioc_sain_fiche_d_taill_e_militant_cvav_platform", titre: "Registre dioc sain fiche d taill e militant cvav platform", domaine: "Espace Militant" },
  { slug: "registre_dioc_sain_modale_d_dition_du_dossier_militant", titre: "Registre dioc sain modale d dition du dossier militant", domaine: "Espace Militant" },
  { slug: "registre_filtr_demandes_en_instance_curiale_section_approved_cath_drale_christ", titre: "Registre filtr demandes en instance curiale section approved cath drale christ", domaine: "Registres & Tabularium" },
  { slug: "registre_paroissial_consolid_144_cartes_mises_cath_drale_christ_roi", titre: "Registre paroissial consolid 144 cartes mises cath drale christ roi", domaine: "Registres & Tabularium" },
  { slug: "registre_paroissial_consolid_des_adh_sions_valid_es_cath_drale_christ_roi", titre: "Registre paroissial consolid des adh sions valid es cath drale christ roi", domaine: "Registres & Tabularium" },
  { slug: "registre_paroissial_consolid_des_cartes_mises_berthe_marie_dje_ajout_e_cath", titre: "Registre paroissial consolid des cartes mises berthe marie dje ajout e cath", domaine: "Registres & Tabularium" },
  { slug: "registre_sanitaire_paroissial_protocoles_pai_allergies_filtr_s_cath_drale", titre: "Registre sanitaire paroissial protocoles pai allergies filtr s cath drale", domaine: "Registres & Tabularium" },
  { slug: "registre_sanitaire_paroissial_toutes_les_dispenses_certificats_m_dicaux_cath", titre: "Registre sanitaire paroissial toutes les dispenses certificats m dicaux cath", domaine: "Registres & Tabularium" },
  { slug: "registre_scell_verrouill_patrouille_saint_joseph_25_28", titre: "Registre scell verrouill patrouille saint joseph 25 28", domaine: "Authentification" },
  { slug: "registre_scell_verrouill_patrouille_saint_joseph_28_28", titre: "Registre scell verrouill patrouille saint joseph 28 28", domaine: "Authentification" },
  { slug: "relance_sms_group_e_fiches_sanitaires_manquantes_console_paroissiale", titre: "Relance sms group e fiches sanitaires manquantes console paroissiale", domaine: "Console Paroissiale" },
  { slug: "relev_comparatif_de_p_r_quation_d_canale_pdf_a_3b_dioc_se_de_daloa", titre: "Relev comparatif de p r quation d canale pdf a 3b dioc se de daloa", domaine: "Chancellerie & Bibliothèque" },
  { slug: "reprise_du_jeu_module_terrain_en_s_ance_patrouille_saint_joseph", titre: "Reprise du jeu module terrain en s ance patrouille saint joseph", domaine: "Terrain & Sécurité" },
  { slug: "reversal_dioc_sain_des_60_304_500_fcfa_v_ch_de_daloa", titre: "Reversal dioc sain des 60 304 500 fcfa v ch de daloa", domaine: "Finances & Cotisations" },
  { slug: "saisie_des_pr_sences_wf_09_dispense_valid_e_pr_sence_enregistr_e_patrouille", titre: "Saisie des pr sences wf 09 dispense valid e pr sence enregistr e patrouille", domaine: "Gouvernance & Synodalité" },
  { slug: "saisie_des_pr_sences_wf_09_espace_chef_de_patrouille_1", titre: "Saisie des pr sences wf 09 espace chef de patrouille 1", domaine: "Gouvernance & Synodalité" },
  { slug: "saisie_des_pr_sences_wf_09_espace_chef_de_patrouille_2", titre: "Saisie des pr sences wf 09 espace chef de patrouille 2", domaine: "Gouvernance & Synodalité" },
  { slug: "saisie_des_pr_sences_wf_09_modale_de_justification_avec_certificat_m_dical_jean", titre: "Saisie des pr sences wf 09 modale de justification avec certificat m dical jean", domaine: "Gouvernance & Synodalité" },
  { slug: "saisie_des_pr_sences_wf_09_simulation_militant_absent_avec_motif_patrouille", titre: "Saisie des pr sences wf 09 simulation militant absent avec motif patrouille", domaine: "Espace Militant" },
  { slug: "scellement_archivage_canonique_grand_camp_pascal_2025", titre: "Scellement archivage canonique grand camp pascal 2025", domaine: "Camps & Pèlerinages" },
  { slug: "scellement_balise_3_points_attribu_s_quipe_alpha_lion_courageux", titre: "Scellement balise 3 points attribu s quipe alpha lion courageux", domaine: "Camps & Pèlerinages" },
  { slug: "scellement_canonique_confirm_certificat_notari_grand_camp_pascal_2025", titre: "Scellement canonique confirm certificat notari grand camp pascal 2025", domaine: "Camps & Pèlerinages" },
  { slug: "simulation_d_impression_directe_plein_cran_quittance_a4_mo_se_assi", titre: "Simulation d impression directe plein cran quittance a4 mo se assi", domaine: "Finances & Cotisations" },
  { slug: "simulation_d_impression_directe_plein_cran_spooler_a4_300_dpi", titre: "Simulation d impression directe plein cran spooler a4 300 dpi", domaine: "Chancellerie & Bibliothèque" },
  { slug: "simulation_de_restauration_en_bac_sable_sandbox_pca_dioc_se_de_daloa", titre: "Simulation de restauration en bac sable sandbox pca dioc se de daloa", domaine: "Statistiques & Pilotage" },
  { slug: "succ_s_carte_provisoire_cvav_platform", titre: "Succ s carte provisoire cvav platform", domaine: "Console Paroissiale" },
  { slug: "succ_s_carte_provisoire_dioc_se_de_daloa_wf_04", titre: "Succ s carte provisoire dioc se de daloa wf 04", domaine: "Console Paroissiale" },
  { slug: "suivi_des_demandes_scr_cer_02_statut_section_approved_mo_se_assi", titre: "Suivi des demandes scr cer 02 statut section approved mo se assi", domaine: "Console Paroissiale" },
  { slug: "suivi_en_direct_des_inscriptions_paroissiales_48_paroisses_p_lerinage_2025", titre: "Suivi en direct des inscriptions paroissiales 48 paroisses p lerinage 2025", domaine: "Portail & Inscriptions" },
  { slug: "suivi_filtr_doyenn_s_ruraux_ouest_nord_p_r_quation_active_p_lerinage_2025", titre: "Suivi filtr doyenn s ruraux ouest nord p r quation active p lerinage 2025", domaine: "Camps & Pèlerinages" },
  { slug: "suivi_filtr_paroisses_faible_mobilisation_30_p_lerinage_2025", titre: "Suivi filtr paroisses faible mobilisation 30 p lerinage 2025", domaine: "Camps & Pèlerinages" },
  { slug: "t_l_chargement_consultation_certificat_de_scellement_bak_2025_0815_full_dioc_se", titre: "T l chargement consultation certificat de scellement bak 2025 0815 full dioc se", domaine: "Registres & Tabularium" },
  { slug: "t_l_chargement_du_fichier_pdf_a_3b_haute_d_finition_feuille_d_margement_d_issia", titre: "T l chargement du fichier pdf a 3b haute d finition feuille d margement d issia", domaine: "Chancellerie & Bibliothèque" },
  { slug: "t_l_chargement_du_fichier_pdf_a_3b_haute_d_finition_feuille_d_margement_issia", titre: "T l chargement du fichier pdf a 3b haute d finition feuille d margement issia", domaine: "Chancellerie & Bibliothèque" },
  { slug: "t_l_chargement_du_fichier_pdf_a_haute_d_finition_certificat_notari_canonique", titre: "T l chargement du fichier pdf a haute d finition certificat notari canonique", domaine: "Chancellerie & Bibliothèque" },
  { slug: "t_l_chargement_inspection_cl_x.509.cer_abb_paul_marie_gnamien", titre: "T l chargement inspection cl x.509.cer abb paul marie gnamien", domaine: "Chancellerie & Bibliothèque" },
  { slug: "t_l_chargement_inspection_du_certificat_x.509.cer_dr._yao_koffi", titre: "T l chargement inspection du certificat x.509.cer dr. yao koffi", domaine: "Chancellerie & Bibliothèque" },
  { slug: "t_l_chargement_inspection_du_certificat_x.509.cer_mgr_jean_baptiste_akwaba", titre: "T l chargement inspection du certificat x.509.cer mgr jean baptiste akwaba", domaine: "Chancellerie & Bibliothèque" },
  { slug: "t_l_chargement_inspection_locale_du_certificat_x.509.cer_fr._jean_marc_koffi", titre: "T l chargement inspection locale du certificat x.509.cer fr. jean marc koffi", domaine: "Chancellerie & Bibliothèque" },
  { slug: "t_l_chargement_pack_7_ordres_de_mission_pdf_a_3b_group_p_lerinage_2025", titre: "T l chargement pack 7 ordres de mission pdf a 3b group p lerinage 2025", domaine: "Chancellerie & Bibliothèque" },
  { slug: "tableau_de_bord_administrateur_doyenn_scr_dash_doy_doyenn_centre", titre: "Tableau de bord administrateur doyenn scr dash doy doyenn centre", domaine: "Assainissement" },
  { slug: "tableau_de_bord_administrateur_doyenn_scr_dash_doy_doyenn_centre_daloa", titre: "Tableau de bord administrateur doyenn scr dash doy doyenn centre daloa", domaine: "Assainissement" },
  { slug: "tableau_de_bord_administrateur_paroissial_scr_dash_par_cath_drale_christ_roi", titre: "Tableau de bord administrateur paroissial scr dash par cath drale christ roi", domaine: "Assainissement" },
  { slug: "tableau_de_bord_paroissial_chef_de_section_cvav_1", titre: "Tableau de bord paroissial chef de section cvav 1", domaine: "Assainissement" },
  { slug: "tableau_de_bord_paroissial_chef_de_section_cvav_2", titre: "Tableau de bord paroissial chef de section cvav 2", domaine: "Assainissement" },
  { slug: "tableau_de_bord_superadmin_cvav_dioc_se_de_daloa", titre: "Tableau de bord superadmin cvav dioc se de daloa", domaine: "Assainissement" },
  { slug: "tirage_group_termin_3_3_cartes_pvc_pr_tes_badgeuse_evolis_cath_drale_christ_roi", titre: "Tirage group termin 3 3 cartes pvc pr tes badgeuse evolis cath drale christ roi", domaine: "Pédagogie & Investiture" },
  { slug: "transfert_paroissial_valid_fusion_scell_e_wf_02a_ange_gabriel_traor", titre: "Transfert paroissial valid fusion scell e wf 02a ange gabriel traor", domaine: "Gouvernance & Synodalité" },
  { slug: "transmission_du_bordereau_consolid_la_curie_dioc_saine_issia_98_militants", titre: "Transmission du bordereau consolid la curie dioc saine issia 98 militants", domaine: "Espace Militant" },
  { slug: "v_rification_publique_d_attestation_brevet_scr_pub_01_mo_se_assi", titre: "V rification publique d attestation brevet scr pub 01 mo se assi", domaine: "Camps & Pèlerinages" },
  { slug: "validation_balise_3_nfc_qr_quipe_alpha_lion_courageux", titre: "Validation balise 3 nfc qr quipe alpha lion courageux", domaine: "Terrain & Sécurité" },
  { slug: "validation_cotisation_confirmation_cvav_platform", titre: "Validation cotisation confirmation cvav platform", domaine: "Finances & Cotisations" },
  { slug: "validation_des_pr_inscriptions_doublons_wf_03_wf_02_admin_paroisse", titre: "Validation des pr inscriptions doublons wf 03 wf 02 admin paroisse", domaine: "Portail & Inscriptions" },
  { slug: "validation_finale_des_affectations_ordres_de_mission_sms_d_livr_s_p_lerinage", titre: "Validation finale des affectations ordres de mission sms d livr s p lerinage", domaine: "Camps & Pèlerinages" },
  { slug: "validation_r_ussie_carte_mise_ange_emmanuel_kouame_console_admin", titre: "Validation r ussie carte mise ange emmanuel kouame console admin", domaine: "Console Paroissiale" },
  { slug: "validation_r_ussie_envoi_badgeuse_pvc_jean_philippe_kanga", titre: "Validation r ussie envoi badgeuse pvc jean philippe kanga", domaine: "Pédagogie & Investiture" },
  { slug: "validation_r_ussie_impression_carte_pvc_en_cours_berthe_dje", titre: "Validation r ussie impression carte pvc en cours berthe dje", domaine: "Pédagogie & Investiture" },
  { slug: "validation_r_ussie_ordre_de_gravure_transmis_amenan_gr_ce_brou", titre: "Validation r ussie ordre de gravure transmis amenan gr ce brou", domaine: "Console Paroissiale" },
  { slug: "visa_sacerdotal_group_de_l_aum_nier_scr_cer_05_cath_drale_christ_roi", titre: "Visa sacerdotal group de l aum nier scr cer 05 cath drale christ roi", domaine: "Console Paroissiale" },
  { slug: "visa_sacerdotal_valid_statut_approved_3_dossiers_scell_s_cath_drale_christ_roi", titre: "Visa sacerdotal valid statut approved 3 dossiers scell s cath drale christ roi", domaine: "Console Paroissiale" },
  { slug: "visionneuse_d_aper_u_rapide_du_fichier_csv_registre_paroissial_consolid", titre: "Visionneuse d aper u rapide du fichier csv registre paroissial consolid", domaine: "Registres & Tabularium" },
  { slug: "visionneuse_d_aper_u_rapide_du_fichier_csv_vue_csv_brut_registre_paroissial", titre: "Visionneuse d aper u rapide du fichier csv vue csv brut registre paroissial", domaine: "Registres & Tabularium" },
];
